name: estq_negativo_up

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 5am GMT-3

permissions: write-all

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl xlrd webdriver-manager gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client packaging

      - name: Run Selenium Scraper
        env:
          #sci_user: ${{ secrets.SCI_USER }}
          #sci_password: ${{ secrets.SCI_PASSWORD }}
        #run: python scripts/info_downloads/raw_users_sci.py
          trier_user: ${{ secrets.TRIER_USER }}
          trier_password: ${{ secrets.TRIER_PASSWORD }}
        run: python scripts/info_downloads/raw_comissao_vendedor.py

      - name: Process and Upload to Google Sheets
        env:
          GSA_CREDENTIALS: ${{ secrets.GSA_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        #run: python scripts/file_processing/sci_users_proc.py
